CREATE DATABASE IF NOT EXISTS DIRECCIONES_DB;

USE DIRECCIONES_DB;

CREATE TABLE IF NOT EXISTS DIRECCIONES (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CALLE VARCHAR(45) DEFAULT NULL,
    NUMERO INT(5) DEFAULT NULL
);

DESCRIBE DIRECCIONES;

INSERT INTO DIRECCIONES (CALLE, NUMERO) VALUES ('Av. Siempre Viva', 742);
INSERT INTO DIRECCIONES (CALLE, NUMERO) VALUES ('Calle Falsa', 123);
INSERT INTO DIRECCIONES (CALLE, NUMERO) VALUES ('Boulevard de los Sueños', 456);